### ISSUE TITLE
Warnings positioned incorrectly when input is contained in a CSS grid

### ISSUE THREAD

**Issue by Rhys-T** [hyperform/hyperform#127]
If the parent element of an `input` is set as `display: grid`, the warning for that input will show up in the wrong place - usually the top-left corner of that grid. This behavior seems to be consistent between Firefox, Chrome, and Safari.

It looks like Hyperform is setting the warning to `position: absolute` without setting specific coordinates for it, which would normally result in the warning ending up wherever it would have stacked up as a `position: static` box - i.e. right under the input. However, when the warning is inside a grid, that default position seems to instead be the top-left corner of the grid.

If the grid has `align-items`/`justify-items` set, or the warning itself has `align-self`/`justify-self`, this position can end up being at the center, bottom, and/or right of the grid instead. However, it never seems to stretch the warning like a normal grid item, regardless of the values of those properties. Setting 

In some cases, I can work around it by wrapping the inputs in non-grid `div`s. That way, the warnings end up inside those wrappers, and are positioned normally. However, this adds complexity to the DOM, and also keeps the grid from directly controlling the size of those inputs.

Minimal example: https://jsbin.com/xavopunemo/edit?html,css,js,output

<details>
<summary>Example source, in case that JSBin doesn't work for some reason</summary>

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/hyperform@0.12.1/css/hyperform.css">
	<style>
		form {
			display: grid;
		}
	</style>
	<p>Try submitting this form without filling in the field. The warning will cover up the input.</p>
	<form action="">
		<input type="text" name="xyz" required>
		<button type="submit">Submit</button>
	</form>
	<script src="https://cdn.jsdelivr.net/npm/hyperform@0.12.1/dist/hyperform.js"></script>
	<script>
		hyperform(window);
	</script>
</body>
</html>
```

</details>

**Comment by Boldewyn** [comment]
Hm. I’m a bit at a loss at what should be fixed/changed at the library level. Given that the concrete styles on any given page can have all kind of side effects, it seems futile to cater for them one by one.

There is already the possibility to adapt the way error message nodes are attached to the DOM: https://hyperform.js.org/examples.html#file=global_message
Maybe that’s a better way to handle the issue? I.e., place the message somewhere else in the DOM outside the grid?

In that case the specifics of Hyperform’s API are detailed at https://hyperform.js.org/docs/high_level_api.html#move-around-or-manipulate-the-error-message

If that doesn’t fix your problem I’d love to hear how I could concretely help you in this case.

**Comment by Rhys-T** [comment]
Yeah, that makes sense. There's only so much the library can do to keep the page from breaking it. 😄

Thanks for pointing out the renderer hooks, though - I hadn't taken in the fact that those existed. I think I have some ideas on how to use those to get the warnings to show up in the right place. I'll reply here again once I've had a chance to work out the details and test it out.

**Comment by Rhys-T** [comment]
The `attachWarning` renderer hook was exactly what I needed. I was able to implement custom positioning for the warnings that works correctly in grids.

<details>
<summary>Details of the workaround I'm using, in case anyone else is trying to use Hyperform with grids</summary>

### HTML (example)

```html
<form id="someForm" action="https://foo.bar.example/whatever" method="post">
	<label for="name">Name:</label>
	<input type="text" id="name" name="name" required>
	<label for="email">Email address:</label>
	<input type="email" id="email" name="email" required>
	<button type="submit">Submit</button>
</form>
```

### JavaScript

```js
hyperform(window);
/*
Workaround for <https://github.com/hyperform/hyperform/issues/127>.

Hyperform just sets its warnings as position: absolute without
setting coordinates for them. Normally, that just puts it
'wherever it would be' - i.e. right below the input - but when
the input is a grid item, the warning ends up defaulting to the
upper-left-corner of the grid.

With this renderer hook installed, warnings for grid-based inputs
will instead end up inside wrapper elements which are assigned to
the same grid areas as the corresponding inputs. The warnings are
positioned so that their top edges sit at the bottom of the grid
cells, thus placing them below the inputs.

Limitations:
- This code assumes you're positioning the inputs with grid-area,
  not numeric row/column or auto-layout. Can probably be adapted.
- If the input is smaller than the grid cell, the warning may
  appear too far away from it. Not sure what to do about that.
- It relies on classList. That should be supported in just about
  anything that supports grid, but if not, it can be changed to
  just use className.
*/
const hfWarningGridWrapperClass = 'hfWarningGridWrapper';
const hfGridAreaProperty = '--hf-grid-area';
hyperform.setRenderer('attachWarning', (warning, input) => {
	/*
	getComputedStyle's behavior for shorthand properties like grid-area is
	apparently somewhat inconsistent, so I'm using a custom property instead.
	It should be set to the same thing as grid-area on each input.
	*/
	const gridArea = getComputedStyle(input).getPropertyValue(hfGridAreaProperty);
	if(gridArea) {
		/** @type {HTMLElement} */
		let wrapper = input.nextElementSibling;
		if(wrapper) {
			if(!wrapper.classList.contains(hfWarningGridWrapperClass)) {
				wrapper = undefined;
			}
		}
		if(!wrapper) {
			wrapper = document.createElement('div');
			wrapper.className = hfWarningGridWrapperClass;
			wrapper.role = 'presentation';
			wrapper.style.gridArea = gridArea;
			input.parentNode.insertBefore(wrapper, input.nextSibling);
		}
		wrapper.insertBefore(warning, null);
	} else {
		// Not in a grid, so just insert it in the default location
		input.parentNode.insertBefore(warning, input.nextSibling);
	}
});
```

### CSS

```css
.hfWarningGridWrapper {
	position: relative;
	pointer-events: none;
	align-self: stretch;
	justify-self: stretch;
}

/*
This is copied from the official hyperform.css and adapted for use with the grid wrappers.
I'm not splitting the .hf-invalid and :invalid rules like that does, however, since IE9 doesn't support grid anyway.
*/
.hf-invalid + .hfWarningGridWrapper .hf-warning,
:invalid + .hfWarningGridWrapper .hf-warning {
	display: none;
	position: absolute;
	top: 100%;
	left: 0;
}
.hf-invalid:focus + .hfWarningGridWrapper .hf-warning,
:invalid:focus + .hfWarningGridWrapper .hf-warning {
	display: block;
}

/* Everything below this point is example code that goes with the HTML above */
#someForm {
	display: grid;
	grid-template:
		"nameLabel	name"	auto
		"emailLabel	email"	auto /
		auto		1fr
	;
}
label[for="name"] {
	grid-area: nameLabel;
	--hf-grid-area: nameLabel;
}
#name {
	grid-area: name;
	--hf-grid-area: name;
}
label[for="email"] {
	grid-area: emailLabel;
	--hf-grid-area: emailLabel;
}
#email {
	grid-area: email;
	--hf-grid-area: email;
}
```

</details>
